# Change these first
owner: u4gbot # Your GitHub username
repo: status.webodm.net

# Add your sites here
sites:
  - name: Processing Network (spark1)
    url: https://spark1.webodm.net
    expectedStatusCodes:
      - 200
      - 401
  - name: Dashboard
    url: https://webodm.net
  - name: Cloud Platform 1
    url: https://cloud1.webodm.net/login/
  - name: S3 Storage
    url: https://wln.s3.webodm.net/test.txt
  - name: S4 Storage
    url: https://wln.s4.webodm.net/test.txt
    
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.webodm.net
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  # logoUrl: ""
  name: WebODM Lightning
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: ""
